In [ ]:
# Utwórz tablicę NumPy zawierającą liczby od 1 do 100. Oblicz i wypisz:
# Wymagania:
# Sumę wszystkich elementów
# Średnią arytmetyczną
# Medianę
# Wartość maksymalną i minimalną
# Użyj np.arange() do stworzenia tablicy
# Użyj funkcji agregujących NumPy ( np.sum , np.mean , etc.)

import numpy as np

tablica = np.arange(1,101)
print(f"Tablica: {tablica}")
print(f"Suma wszystkich elementów: {np.sum(tablica)}")
print(f"Średnia arytmetyczna: {np.mean}")
print(f"Mediana: {np.median(tablica)}")
print(f"Wartość maksymalna: {np.max(tablica)}, wartość minimalna: {np.min(tablica)}")

Tablica: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Suma wszystkich elementów: 5050
Średnia arytmetyczna: <function mean at 0x000001DB0F6A2AC0>
Mediana: 50.5
Wartość maksymalna: 100, wartość minimalna: 1


In [ ]:
# Masz dwie tablice reprezentujące ceny produktów przed i po rabacie:
# Oblicz i wypisz:
# before = np.array([100, 250, 75, 320, 180, 450, 90])
# after = np.array([80, 200, 60, 280, 150, 400, 75])
# Wymagania:
# Różnicę między cenami (oszczędności)
# Procent rabatu dla każdego produktu
# Średnią oszczędność
# # Użyj operacji wektorowych (bez pętli)
# Wynik zaokrąglij do 2 miejsc po przecinku

import numpy as np

before = np.array([100, 250, 75, 320, 180, 450, 90])
print(f"Before: {before}")
after = np.array([80, 200, 60, 280, 150, 400, 75])
print(f"After: {after}")
print(f"Różnica między cenami: {before - after}")
print(f"Procent rabatu: {np.round((100 - ((after * 100) / before)), 2)}")

Before: [100 250  75 320 180 450  90]
After: [ 80 200  60 280 150 400  75]
Różnica między cenami: [20 50 15 40 30 50 15]
Procent rabatu: [20.   20.   20.   12.5  16.67 11.11 16.67]


In [12]:
# Dana tablica 1D:
# # Wykonaj:
# temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])
# Wypisz temperatury z dni parzystych (0, 2, 4, ...)
# Wypisz ostatnie 5 temperatur
# Wypisz temperatury w odwrotnej kolejności
# Znajdź temperatury większe niż 20

import numpy as np

temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])
print("Temperatura w dni parzyste:", temps[::2])
print("Temperatura w odwrotnej kolejności:", temps[::-1])
x = temps[temps >= 20]
print("Temperatury wyższe niż 20", x)

Temperatura w dni parzyste: [15 22 23 17 16 21]
Temperatura w odwrotnej kolejności: [24 21 19 16 14 17 20 23 25 22 18 15]
Temperatury wyższe niż 20 [22 25 23 20 21 24]


In [2]:
# Utwórz tablicę 2D (5x4) wypełnioną losowymi liczbami całkowitymi od 1 do 50.
# Wymagania:
# Użyj np.random.randint()
# Wypisz shape tablicy
# Wypisz drugi wiersz
# Wypisz trzecią kolumnę
# Wypisz element z pozycji (2, 3)

import numpy as np

tablica = np.random.randint(1,51, size = (5, 4))
print(tablica)
print(tablica.shape)
print("Liczby losowe w drugim wierszu:", tablica[1])
print("Liczby losowe w trzeciej kolumnie:", tablica[:,2])
print("liczba z pozycji(2,3):", tablica[1,2])

[[11 13 37 22]
 [47 38 23  5]
 [ 6  5  2 34]
 [ 3 28  6 46]
 [46 24 50 19]]
(5, 4)
Liczby losowe w drugim wierszu: [47 38 23  5]
Liczby losowe w trzeciej kolumnie: [37 23  2  6 50]
liczba z pozycji(2,3): 23


In [20]:
# Dana tablica reprezentująca sprzedaż 4 produktów w 7 dni:
# sales = np.random.randint(10, 100, size=(4, 7))
# Oblicz i wypisz:
# Średnią sprzedaż per produkt (axis=1)
# Średnią sprzedaż per dzień (axis=0)
# Dzień z najwyższą sprzedażą (np.argmax)
# Produkt z najniższą średnią sprzedażą

import numpy as np

sales = np.random.randint(10, 100, size=(4, 7))
print(sales)
srednia_sales = np.mean((sales), axis=1)
print("Średnia sprzedaż per produkt:", srednia_sales)
srednia_dzien = np.mean((sales), axis=0)
print("Średnia sprzedaż per dzień:", srednia_dzien)
day1 = np.sum(sales[: ,0])
day2 = np.sum(sales[: ,1])
day3 = np.sum(sales[: ,2])
day4 = np.sum(sales[: ,3])
day5 = np.sum(sales[: ,4])
day6 = np.sum(sales[: ,5])
day7 = np.sum(sales[: ,6])

days = ([
    [day1],
    [day2],
    [day3],
    [day4],
    [day5],
    [day6],
    [day7]
])
high_sales = np.argmax(days)
print("Najwyższa sprzedaś w dniu", high_sales)


[[74 67 11 26 10 95 51]
 [51 15 62 39 34 50 61]
 [59 33 16 98 37 41 84]
 [24 55 18 32 82 43 37]]
Średnia sprzedaż per produkt: [47.71428571 44.57142857 52.57142857 41.57142857]
Średnia sprzedaż per dzień: [52.   42.5  26.75 48.75 40.75 57.25 58.25]
Najwyższa sprzedaś w dniu 6


In [32]:
# Masz tablicę z oceną studentów:
# Wykonaj:
# grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])
# Znajdź wszystkie oceny >= 80 (oceny wysokie)
# Znajdź wszystkie oceny < 50 (oceny niedostateczne)
# Policz ile jest ocen w przedziale [60, 80)
# Zmień wszystkie oceny < 50 na 50 (podniesienie do minimum)

import numpy as np

grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])
oceny_wysokie = grades[grades >= 80] 
print("Wysokie oceny:", oceny_wysokie)
oceny_niedostateczny = grades[grades < 50]
print("Oceny niedostateczny:", oceny_niedostateczny)
oceny_przedzial = np.sum((grades >= 60) & (grades <= 80))
print("Ilość ocen w przedziale (60, 80):", oceny_przedzial)


Wysokie oceny: [92 88 91 85 95]
Oceny niedostateczny: [45 34 23]
Ilość ocen w przedziale (60, 80): 3


In [37]:
# Utwórz następujące macierze:
# Wymagania:
# Macierz 3x3 wypełnioną zerami
# Macierz 4x4 wypełnioną jedynkami
# Macierz identyczności 5x5
# Macierz 3x4 wypełnioną liczbą 7
# Wektor 10 równoodległych wartości od 0 do 1
# Użyj np.zeros , np.ones , np.eye , np.full , np.linspace

import numpy as np

macierz1 = np.zeros((3,3))
print("Macierz:\n", macierz1)
macierz2 = np.ones((4, 4))
print("Macierz:\n", macierz2)
identity = np.eye((5))
print("Macierz identyczności:\n", identity)
macierz3 = np.full((3, 4), 7)
print("Macierz:\n", macierz3)

Macierz:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Macierz:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Macierz identyczności:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Macierz:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# Dana tablica ocen (5 studentów x 4 egzaminy):
# Dodaj bonus do każdego egzaminu: [5, 10, 5, 10]
# Następnie pomnóż wyniki każdego studenta przez mnożnik: [1.0, 1.1, 0.95, 1.15, 1.0]
# Wymagania:
# Użyj broadcastingu (bez pętli)
# Wypisz wyniki przed i po
import numpy as np

exams = np.array([
[78, 85, 92, 88],
[65, 72, 68, 70],
[90, 88, 95, 92],
[55, 60, 58, 62],
[82, 79, 85, 80]
])
print("Wyniki egzaminów:")
print(exams)

bonus = np.array([5, 10, 5, 10])
print("Bonus:", bonus)

bonus_egzamin = exams + bonus
print("Wyniki egzaminów z bonusem:")
print(bonus_egzamin)

mnoznik = np.array([1.0, 1.1, 0.95, 1.15, 1.0]).reshape(5,1)
print("Monożnik:")
print(mnoznik)

wynik_mnoznika = exams * mnoznik
print("Po przemnożeniu:")
print(wynik_mnoznika)


Wyniki egzaminów:
[[78 85 92 88]
 [65 72 68 70]
 [90 88 95 92]
 [55 60 58 62]
 [82 79 85 80]]
Bonus: [ 5 10  5 10]
Wyniki egzaminów z bonusem:
[[ 83  95  97  98]
 [ 70  82  73  80]
 [ 95  98 100 102]
 [ 60  70  63  72]
 [ 87  89  90  90]]
Monożnik:
[[1.  ]
 [1.1 ]
 [0.95]
 [1.15]
 [1.  ]]
Po przemnożeniu:
[[78.   85.   92.   88.  ]
 [71.5  79.2  74.8  77.  ]
 [85.5  83.6  90.25 87.4 ]
 [63.25 69.   66.7  71.3 ]
 [82.   79.   85.   80.  ]]


In [ ]:
# Dataset: Sprzedaż 6 produktów w 30 dni
# Oblicz:
# sales = np.random.randint(50, 200, size=(6, 30))
# Trend sprzedaży per produkt (różnica między ostatnimi 7 dniami a pierwszymi 7 dniami)
# Najlepszy tydzień (dni 0-6, 7-13, 14-20, 21-27) dla całej sprzedaży
# Wykres: sprzedaż per produkt w czasie (linie)
# Użyj slicingu do wycinania tygodni
# Wizualizacja matplotlib
import numpy as np
import matplotlib.pyplot as plt

sales = np.random.randint(50, 200, size=(6, 30))
print("sales:")
print(sales)

last_week = np.sum(sales[:,-7:], axis=1)
print("ostatnie:")
print(last_week)

first_week = np.sum(sales[:,0:7],axis=1)
print("Pierwsze:")
print(first_week)

roznica = last_week - first_week
print("Różnica:")
print(roznica)

week1 = np.sum(sales[:, 0:7])
week2 = np.sum(sales[:, 7:14])
week3 = np.sum(sales[:, 14:21])
week4 = np.sum(sales[:, 21:28])

weeks = np.array([
    [week1],
    [week2],
    [week3],
    [week4],
])

naj_tydz = np.argmax(weeks)
print("Najlepszy tydzień to tydzień numer:", naj_tydz + 1)



sales:
[[151 137  83 158 195  75  60 122  93  90 138 147  67 142  95 188 100 160
  156 127 116 156 159 178 197  93 130 112 167 119]
 [190 131 174 153  86 134 158 153 180  87  55 172 117 143 156 103  53  71
  166  84 149  84  58 196 177 125 149 128 171 126]
 [ 66 134 146 159  76 131 140 121 100 129 128 135 113 112  98 125 186 132
   86 123 157 163 160 117 160 159  79  66 191 193]
 [176  74 196 108  87 165 167 189 115 150 121 170 167  79 148 196 185 146
   95 115 131 189 187 106 183 135  60 121 182 155]
 [ 68 111 115 129  69 148 125 172 166 111 110 159 139 195 131  88  74  94
  190 199 177 119  96 161 143 193 126 183 111  74]
 [186 166 117  60 152 178 180 149 178 183 156  66 178 191 133 192 151  60
   71 130 151 173 102 137 139  75 175 191 178 141]]
ostatnie:
[ 996 1072  965  942  991 1036]
Pierwsze:
[ 859 1026  852  973  765 1039]
Różnica:
[137  46 113 -31 226  -3]
Najlepszy tydzień to tydzień numer: 4
